export const ClassNamesValues: { [key: string]: [string, string] } = {
  "important-font-color": ["black", "color"],
  "lessimportant-font-color": ["rgb(80, 80, 80)", "color"],
  background: ["rgb(255,255,255)", "background"],
  "background-alternative": ["whitesmoke", "background"],
  "background-button": ["rgb(255,255,255)", "background"],
  "background-button-active": ["rgb(0, 72, 255)", "background"],
  "text-color-button": ["rgb(170, 170, 170)", "color"],
  "text-color-button-active": ["rgb(255,255,255)", "color"],
  "link-color": ["black", "color"],
  "link-color-active": ["black", "color"],
  "radial-gradient": [
    "radial-gradient(circle at top right, rgba(255,106,0,1) 10%, transparent 40%), radial-gradient(circle at right, rgba(255,0,0,1) 0%, transparent 60%), radial-gradient(circle at bottom right, rgba(72,0,255,1) 0%, transparent 60%)",
    "background",
  ],
  "linear-gradient": [
    "linear-gradient(36deg, rgba(38,104,255,1) 0%, rgba(178,43,255,1) 100%)",
    "background",
  ],
  "regular-font-weight": ["400", "font-weight"],
  "semi-bold-font-weight": ["600", "font-weight"],
  "bold-font-weight": ["800", "font-weight"],
  "black-box-shadow": ["0px 0px 10px 1px rgba(0,0,0,0.5)", "box-shadow"],
  "black-box-shadow-active": ["0px 0px 20px 2px rgba(0,0,0,0.8)", "box-shadow"],
  "white-box-shadow": ["0px 0px 10px 1px rgba(255,255,255,0.5)", "box-shadow"],
  "white-box-shadow-active": [
    "0px 0px 20px 2px rgba(255,255,255,0.8)",
    "box-shadow",
  ],
  "element-border-radius-size": ["15px", "border-radius"],
  "big-font-size": ["8vw", "font-size"],
  "big-font-size-mobile": ["10vw", "font-size"],
  "semi-big-font-size": ["4vw", "font-size"],
  "semi-big-font-size-mobile": ["8vw", "font-size"],
  "middle-font-size": ["2vw", "font-size"],
  "middle-font-size-mobile": ["6vw", "font-size"],
  "normal-font-size": ["1.5vw", "font-size"],
  "normal-font-size-mobile": ["5.5vw", "font-size"],
  "tiny-font-size": ["0.8vw", "font-size"],
  "tiny-font-size-mobile": ["2.8vw", "font-size"],
  "big-font-size-current": ["8vw", "font-size"],
  "semi-big-font-size-current": ["4vw", "font-size"],
  "middle-font-size-current": ["2vw", "font-size"],
  "normal-font-size-current": ["1.5vw", "font-size"],
  "tiny-font-size-current": ["0.8vw", "font-size"]
};
